### PR TITLE
Add functionality for gripper in rosserial

### PR DESCRIPTION
**Pull request by Jash-Shah**
The major changes are:
- Change `esp_serial.cpp` in both `firmware/3_rosserial_rviz` and `firmware/4_rosserial_gazebo` to include 4th gripper servo
- Change `Testing.py` in `simulation_gazebo` to give angles to the gripper servo
- Change `pub_rviz.py` to publish angles to all gripper joints

### CODE REVIEW

**Comment by gautam-dev-maker** [comment]
@Jash-Shah remove sdkconfig.old, these are redundant files

**Comment by Neel-Shah-29** [comment]
Change forward kinematics such that the gripper opens and closes - Anushree

**Comment by gautam-dev-maker** [comment]
@Jash-Shah is it feasible to add OLED support to rosserial code?

**Comment by Jash-Shah** [comment]
> @Jash-Shah is it feasible to add OLED support to rosserial code?

No, I personally have very little familiarity regarding that part.

**Comment by Jash-Shah** [comment]
Closing this pull request due to unresolvable merge conflicts

**Pull request closed without merging**
