### PR TITLE
Update the Installer script

### PR DESCRIPTION
**Pull request by advait-0**
This Shell Script installs:
1. ROS2 Humble
2. Micro-Ros
3. ESP-IDF v4.4

Configures locale for ROS2, Installs dependencies and binaries.
Also make sourcing easier by integrating source commands into the bashrc

### CODE REVIEW

**Comment by aPR0T0** [comment]
Also add following packages
- ros2_control
- gazebo_ros2_control
- rviz2

**Comment by VedantParanjape** [comment]
Why are there 30 file changes ? Please properly rebase your fork to sync the latest changes and then create a pull request.

**Comment by aPR0T0** [comment]
> Why are there 30 file changes ? Please properly rebase your fork to sync the latest changes and then create a pull request.

Develop branch is already behind the main branch by 30 commits so sync might not help

**Comment by VedantParanjape** [comment]
> > Why are there 30 file changes ? Please properly rebase your fork to sync the latest changes and then create a pull request.
> 
> Develop branch is already behind the main branch by 30 commits so sync might not help

you can sync the develop branch to main and then make a PR. It's impossible to review if so many previous changes are put in.

**Comment by VedantParanjape** [comment]
> > Why are there 30 file changes ? Please properly rebase your fork to sync the latest changes and then create a pull request.
> 
> Develop branch is already behind the main branch by 30 commits so sync might not help

https://github.com/SRA-VJTI/MARIO/tree/ros2-dev

Created a new branch forked from master. Please rebase your changes on this.

**Pull request closed without merging**
